#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ToolBar_MS_Tutorial.Resource", IsApplication=true)]

namespace ToolBar_MS_Tutorial
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070002
			public const int edit_toolbar = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int main_content = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int menu_copy = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int menu_cut = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int menu_edit = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int menu_paste = 2131165189;
			
			// aapt resource value: 0x7f070008
			public const int menu_preferences = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int menu_save = 2131165191;
			
			// aapt resource value: 0x7f070000
			public const int toolbar = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int toolbar = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int edit_menus = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int top_menus = 2131099649;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_content_create = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_content_save = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_menu_copy_holo_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_menu_cut_holo_dark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_menu_paste_holo_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_menu_search_holo_dark = 2130837509;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int MyTheme = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
